# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "falcon", "~> 0.54.2"
gem "sequel", "~> 5.101"
gem "pg", "~> 1.6"
gem "bcrypt", "~> 3.1"
gem "jwt", "~> 3.1"

gem "dotenv", "~> 3.2"

gem "async-websocket", "~> 0.30.0"
